name: Build Docker

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v2
      with:
          context: ./apis/poi/web/
          push: false
          tags: devopsoh/api-poi:${{ github.run_number }}
          
    - name: Unit Testing
      run: |
          dotnet restore ./apis/poi/
          dotnet test ./apis/poi/tests/UnitTests/UnitTests.csproj

  deploy:
    name: Publish to ACR
    runs-on: ubuntu-latest
    needs: setup-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: openhackjap2c1y4acr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name:  Build & Publish
        uses: docker/build-push-action@v2
        with:
            context: ./apis/poi/web/
            push: true
            tags: devopsoh/api-poi:${{ github.run_number }}
