name: Build Docker

on:
  pull_request:
    branches: [main]
    paths:
    - 'apis/poi/**'
    - '.github/workflows/Poi_Docker.yml'
  push:
    branches: [main]
    paths:
    - 'apis/poi/**'
    - '.github/workflows/Poi_Docker.yml'

jobs:
  validate_site:
    name: Publicar en Azure la imagen
    runs-on: ubuntu-latest        
    steps:
      - name: Validar que el sitio en staging este ok        
        run: |
              $(curl -i 'https://openhackjap2c1y4poi-staging.azurewebsites.net/api/healthcheck/poi' 2>/dev/null | grep HTTP/1.1)
