name: Build Docker

on:
  pull_request:
    branches: [main]
    paths:
    - 'apis/poi/**'
    - '.github/workflows/Poi_Docker.yml'
  push:
    branches: [main]
    paths:
    - 'apis/poi/**'
    - '.github/workflows/Poi_Docker.yml'

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Code
      run: |
          dotnet restore ./apis/poi/
          dotnet build ./apis/poi/

    - name: Unit Testing
      run: |
          dotnet test ./apis/poi/tests/UnitTests/UnitTests.csproj

  deploy:
    name: Publish to ACR
    runs-on: ubuntu-latest
    needs: setup-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: openhackjap2c1y4acr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name:  Build & Publish
        uses: docker/build-push-action@v2
        with:
            context: ./apis/poi/web/
            push: true
            tags: openhackjap2c1y4acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}

  publish:
    name: Publish to ACR
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Publish to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackjap2c1y4poi'
          slot-name: 'openhackjap2c1y4poi-staging'
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE_POI }}
          images: openhackjap2c1y4acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}

