name: Build Trips

on:
  pull_request:
    branches: [main]
    paths:
    - 'apis/trips/**'
    - '.github/workflows/TripsAPI.yml'
  push:
    branches: [main]
    paths:
    - 'apis/trips/**'
    - '.github/workflows/TripsAPI.yml'

env:
  IMAGE: static-sites

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name:  Build
      uses: docker/build-push-action@v2
      with:
          context: ./apis/trips/
          push: false
          tags: devopsoh/api-trips:${{ github.run_number }}
          
  deploy:
    name: Publish to ACR 
    runs-on: ubuntu-latest
    needs: setup-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          login-server: openhackjap2c1y4acr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name:  Build & Publish
        uses: docker/build-push-action@v2
        with:
            context: ./apis/trips/
            push: true
            tags: openhackjap2c1y4acr.azurecr.io/devopsoh/api-trips:${{ github.run_number }}
            
  publish:
    name: Publish User Profile
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Publish to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackjap2c1y4trips'
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE_TRIPS }}
          images: openhackjap2c1y4acr.azurecr.io/devopsoh/api-trips:${{ github.run_number }}
            
