name: Build DockerFile for User API

on:
  pull_request:
    branches: [main]
    paths:
    - 'apis/userprofile/**'

env:
  IMAGE: static-sites

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unit Testing
      run: |
          npm run test

    - name:  Build
      uses: docker/build-push-action@v2
      with:
          context: ./apis/userprofile/
          push: false
          tags: devopsoh/api-userprofile:latest
