name: Build DockerFile for User API

on:
  pull_request:
    branches: [main]
    paths:
    - 'apis/userprofile/**'

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Unit Testing
    #   run: |
    #       npm run test --prefix ./apis/userprofile/

    - name:  Build
      uses: docker/build-push-action@v2
      with:
          context: ./apis/userprofile/
          push: false
          tags: devopsoh/api-userprofile:${{ GITHUB_RUN_ID }}
